import Navbar from "@/components/Navbar/Navbar";
import "../styles/global.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <div className="flex flex-grow items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
